# Generated by Django 6.0.2 on 2026-03-01 15:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id_event", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("recomended_number_students", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=512)),
                ("is_scheduled", models.BooleanField(default=False)),
                ("time_on_one_student", models.IntegerField()),
                ("event_location", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id_group", models.AutoField(primary_key=True, serialize=False)),
                ("name_group", models.CharField(max_length=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="GroupFlow",
            fields=[
                ("id_flow", models.AutoField(primary_key=True, serialize=False)),
                ("flow_name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("flow_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id_program", models.AutoField(primary_key=True, serialize=False)),
                ("program_number", models.CharField(max_length=8)),
                ("program_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id_subject", models.AutoField(primary_key=True, serialize=False)),
                ("subject_number", models.CharField(max_length=10)),
                ("subject_name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "employee_number",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("manager", "Manager"),
                        ],
                        default="student",
                        max_length=15,
                    ),
                ),
                ("tel", models.CharField(blank=True, max_length=15)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EventGroup",
            fields=[
                ("id_event_group", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.event"
                    ),
                ),
                (
                    "id_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventFlow",
            fields=[
                ("id_event_flow", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.event"
                    ),
                ),
                (
                    "id_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.groupflow"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="id_flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.groupflow"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="id_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.program"
            ),
        ),
        migrations.CreateModel(
            name="StudentFlow",
            fields=[
                (
                    "id_student_flow",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "id_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.groupflow"
                    ),
                ),
                (
                    "id_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramSubjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.program"
                    ),
                ),
                (
                    "id_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.subject"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="groupflow",
            name="id_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.subject"
            ),
        ),
        migrations.CreateModel(
            name="TeacherSubjects",
            fields=[
                (
                    "id_teacher_subject",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "id_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.subject"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherSubjectsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.event"
                    ),
                ),
                (
                    "id_teacher_subject_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.teachersubjects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "id_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.group"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WroteTime",
            fields=[
                ("id_time", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.CharField(max_length=25)),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentEvent",
            fields=[
                ("id_wrote", models.AutoField(primary_key=True, serialize=False)),
                ("note_student", models.CharField(blank=True, max_length=255)),
                ("note_teacher", models.CharField(blank=True, max_length=255)),
                ("is_visit", models.BooleanField(default=False)),
                ("register_time", models.DateTimeField()),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.event"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.wrotetime"
                    ),
                ),
            ],
        ),
    ]
