# Generated by Django 6.0.2 on 2026-03-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_location",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="recomended_number_students",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_on_one_student",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
