# Generated by Django 6.0.2 on 2026-03-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserGroup",
            new_name="StudentGroup",
        ),
    ]
