# Generated by Django 6.0.2 on 2026-03-01 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_event_event_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentevent",
            name="id_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.event",
            ),
        ),
    ]
