# Generated by Django 6.0.2 on 2026-03-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_studentevent_id_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentevent",
            name="id_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.event",
            ),
        ),
    ]
