# Generated by Django 6.0.2 on 2026-03-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_studentevent_id_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
