# Generated by Django 6.0.2 on 2026-03-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_event_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(max_length=100),
        ),
    ]
